# Basics of Pytorch

In [2]:
import numpy as np
import torch

# which torch version
print(f"Using Pytorch {torch.__version__}")
# is a GPU available?
print(f"GPU available? {'😎' if torch.cuda.is_available() else '😪'}")

Using Pytorch 2.6.0+cu126
GPU available? 😎


In [3]:
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [4]:
narr = np.array(arr)
print(narr)

[[1 2]
 [3 4]]


In [5]:
tarr = torch.Tensor(arr)
print(tarr)

tensor([[1., 2.],
        [3., 4.]])


In [10]:
# generating random numbers in Numpy
arr1 = np.random.rand(2, 2)
arr1

array([[0.5375864 , 0.42999613],
       [0.84212135, 0.88009421]])

In [11]:
tarr1 = torch.rand(2, 2)
tarr1

tensor([[0.8179, 0.8498],
        [0.9214, 0.7673]])

In [13]:
# seeding to get reproducible numbers
SEED = 41
np.random.seed(SEED)

In [17]:
np.random.seed(SEED)
arr2 = np.random.rand(2, 2)
arr2

array([[0.25092362, 0.04609582],
       [0.67681624, 0.04346949]])

In [19]:
torch.manual_seed(SEED)
tarr2 = torch.rand(2, 2)
tarr2

tensor([[0.2364, 0.2266],
        [0.8005, 0.1692]])