In [1]:
import numpy as np
import pandas as pd
import torch

print(f"Using torch: {torch.__version__}")

import torch_training_toolkit as t3
print(t3.about())

Using torch: 2.1.2+rocm5.6

Torch Training Toolkit (t3): a library to make training, evaluating & predicting of Pytorch models easier.
Created by Manish Bhobé, and released by Nämostuté Ltd. with MIT Licence (for personal or commercial use).
Use at your own risk. Manish Bhobé (or Nämostuté Ltd.) are not liable for any damages from use of this software!


In [2]:
lst = [1,2,3,4,5,6,7,8,9]  
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
tt = torch.from_numpy(arr)
tt, tt.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.int64)

In [4]:
# you can select data in torch similar to how you select in Numpy
arr[:2], tt[:2], arr[-1:], tt[-1:], arr[2::2], tt[2::2]

(array([1, 2]),
 tensor([1, 2]),
 array([9]),
 tensor([9]),
 array([3, 5, 7, 9]),
 tensor([3, 5, 7, 9]))

In [5]:
t = torch.arange(0, 15).view(5, 3)
t.shape, t

(torch.Size([5, 3]),
 tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]]))